version: "3.7"

services:

  bmfrontend:
    build: bmfrontend/.
    container_name: monkeyfrontend
    ports:
      - 3005:3004
    environment: 
      REACT_APP_SERVER_URL: http://localhost:8082
    command: yarn start
    tty: true
    restart: always
    networks: 
      - frontend
    depends_on: 
      - bmbackend

  bmbackend:
    build: bmbackend/.
    container_name: monkeybackend
    ports:
      - 8082:8081
    tty: true
    restart: always
    environment: 
      # SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test_db
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5435/test_db
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: userpass
    depends_on: 
      - db
    networks:
      - frontend
      - backend

  db:
    image: postgres:13.1
    container_name: monkeydb
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: userpass
      PGPORT: 5435
    ports:
      - "5432:5435"
    volumes:
      - type: bind
        source: C:/Projects/Spielwiese/BMonkey/db/postgres
        target: /var/lib/postgresql/data
    networks:
      - backend

  # db:
  #   image: mysql
  #   container_name: monkeydb
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: test_db
  #     MYSQL_USER: dbuser
  #     MYSQL_PASSWORD: userpass
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_TCP_PORT: 3306
  #   ports:
  #     - "3305:3306"
  #   volumes:
  #     - type: bind
  #       source: C:/Projects/Spielwiese/BMonkey/db/mysql
  #       target: /var/lib/mysql
  #   networks:
  #     - backend

networks:
  backend:
  frontend:   
    