server:
  port: 9091
---
spring:
  cloud:
    gateway:
      routes:
        - id: get
          uri: https://httpbin.org/get
          predicates:
            - Path=/get
#            - Header=AwesomePassword, soso1
