version: "3.8"

services:
  db:
    image: mysql:8.0.22
    container_name: devmysqldb
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3309
    ports:
      - "3309:3309"
    volumes:
      - type: bind
        source: C:/Projects/Spielwiese/BMonkey/db/mysql
        target: /var/lib/mysql
    networks: 
      - bmonkey-net

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
#    networks:
#      - bmonkey-net
networks:
  bmonkey-net:
    driver: "bridge"