version: "3.8"

# volumes:
#   mymymyVol:

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: userpass
    volumes:
      - type: bind
        source: $HOME/Desktop/MySQL-Snippets/school.sql
        target: /data/school.sql
    networks: 
      - bmonkey-net
      # - type: volume
      #   source: mymymyVol

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
networks:
  bmonkey-net:
    driver: "bridge"