version: "3.8"

services:
  db:
    image: postgres:13.1
    container_name: devpostgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: userpass
      PGPORT: 5432
      # PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: C:/Projects/Spielwiese/BMonkey/db/postgres
        target: /var/lib/postgresql/data
    networks: 
      - bmonkey-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - bmonkey-net
networks:
  bmonkey-net:
    driver: "bridge"